//图片路径
var imgData = {
	music:[
		'imgs/music.png',
		'imgs/music_pause.png'
	],
	logo:[
		"imgs/load/logo2.png",
		"imgs/load/logo3.png",
		"imgs/load/logo4.png"
	],
	logoIco:[
		"imgs/load/loadIco1.png",
		"imgs/load/loadIco2.png",
		"imgs/load/loadIco3.png",
		"imgs/load/loadIco4.png",
		"imgs/load/loadIco5.png",
		"imgs/load/loadIco6.png",
		"imgs/load/loadIco7.png",
		"imgs/load/loadIco8.png",
		"imgs/load/loadIco9.png"
	],
	cloud:[
		"imgs/bg/cloud1.png",
		"imgs/bg/cloud2.png",
		"imgs/bg/cloud3.png"
	],
	pageBg:[
		"imgs/bg/bg.jpg"
		],
	bg:[
		"imgs/bg/1.png",
		"imgs/bg/2.png",
		"imgs/bg/3.png",
		"imgs/bg/4.png",
		"imgs/bg/5.png",
		"imgs/bg/6.png",
		"imgs/bg/7.png",
		"imgs/bg/8.png",
		"imgs/bg/9.png",
		"imgs/bg/10.png",
		"imgs/bg/11.png",
		"imgs/bg/12.png",
		"imgs/bg/13.png",
		"imgs/bg/14.png",
		"imgs/bg/15.png",
		"imgs/bg/16.png",
		"imgs/bg/17.png",
		"imgs/bg/18.png",
		"imgs/bg/19.png",
		"imgs/bg/20.png"
	],
	pano:[
		"imgs/pano/p1-1.png",
		"imgs/pano/p1-2.png",
		"imgs/pano/p2-1.png",
		"imgs/pano/p2-2.png",
		"imgs/pano/p2-3.png",
		"imgs/pano/p3-1.png",
		"imgs/pano/p3-2.png",
		"imgs/pano/p3-3.png",
		"imgs/pano/p3-4.png",
		"imgs/pano/p4-1.png",
		"imgs/pano/p4-2.png",
		"imgs/pano/p4-3.png",
		"imgs/pano/p4-4.png",
		"imgs/pano/p4-5.png",
		"imgs/pano/p5-1.png",
		"imgs/pano/p5-2.png",
		"imgs/pano/p5-3.png",
		"imgs/pano/p5-4.png",
		"imgs/pano/p5-5.png",
		"imgs/pano/p5-6.png",
		"imgs/pano/p6-1.png",
		"imgs/pano/p6-2.png",
		"imgs/pano/p6-3.png",
		"imgs/pano/p6-4.png",
		"imgs/pano/p6-5.png",
		"imgs/pano/p6-6.png",
		"imgs/pano/p7-1.png",
		"imgs/pano/p7-2.png",
		"imgs/pano/p7-3.png",
		"imgs/pano/p8-1.png",
		"imgs/pano/p8-2.png",
		"imgs/pano/p8-3.png",
		"imgs/pano/p8-4.png",
		"imgs/pano/p8-5.png",
		"imgs/pano/p8-6.png"
	]
};